// This file is generated by tauri-specta and includes browser-safe fallback handlers.
import { invoke } from "@tauri-apps/api/core";

export interface AppInfo {
  name: string;
  version: string;
  mode: string;
  isElevated: boolean;
}

export interface SystemMetrics {
  cpuUsage: number;
  ramUsedBytes: number;
  ramTotalBytes: number;
  ramUsagePercent: number;
  gpuUsage: number | null;
  gpuTemp: number | null;
  diskFreeBytes: number;
  diskTotalBytes: number;
  diskUsagePercent: number;
  dockerContainers: number;
}

const isTauriEnvironment = () => {
  return typeof window !== "undefined" && "__TAURI_INTERNALS__" in window;
};

export const commands = {
  async getAppInfo(): Promise<AppInfo> {
    if (isTauriEnvironment()) {
      return await invoke<AppInfo>("get_app_info");
    }
    return {
      name: "NetScope",
      version: "0.1.0",
      mode: "simulator",
      isElevated: false,
    };
  },

  async getSystemMetrics(): Promise<SystemMetrics> {
    if (isTauriEnvironment()) {
      return await invoke<SystemMetrics>("get_system_metrics");
    }
    // High-fidelity fallback for web previews matching target visual
    return {
      cpuUsage: 6.4,
      ramUsedBytes: 78_600_000_000,
      ramTotalBytes: 121_700_000_000,
      ramUsagePercent: 66.6,
      gpuUsage: 2.0,
      gpuTemp: 49.0,
      diskFreeBytes: 1_571_100_000_000,
      diskTotalBytes: 3_560_000_000_000,
      diskUsagePercent: 55.9,
      dockerContainers: 17,
    };
  },

  async triggerSimulation(scenario: string): Promise<string> {
    if (isTauriEnvironment()) {
      return await invoke<string>("trigger_simulation", { scenario });
    }
    return `Simulation '${scenario}' triggered`;
  },

  async cleanSimulations(): Promise<string> {
    if (isTauriEnvironment()) {
      return await invoke<string>("clean_simulations");
    }
    return "All simulations cleaned";
  },

  async setTrafficMode(mode: string): Promise<string> {
    if (isTauriEnvironment()) {
      return await invoke<string>("set_traffic_mode", { mode });
    }
    return `Mode switched to ${mode}`;
  },

  async getSocketDelta(): Promise<any> {
    if (isTauriEnvironment()) {
      return await invoke("get_socket_delta");
    }
    return {
      t: Date.now(),
      addNodes: [],
      updateNodes: [],
      removeNodeIds: [],
      addLinks: [],
      updateLinks: [],
      removeLinkIds: [],
    };
  },

  async getSocketSnapshot(): Promise<{ nodes: any[]; links: any[] }> {
    if (isTauriEnvironment()) {
      return await invoke("get_socket_snapshot");
    }
    return { nodes: [], links: [] };
  },

  async getCaptureStatus(): Promise<{
    isAvailable: boolean;
    isActive: boolean;
    driverName: string;
    error: string | null;
    interfaces: string[];
  }> {
    if (isTauriEnvironment()) {
      return await invoke("get_capture_status");
    }
    return {
      isAvailable: false,
      isActive: false,
      driverName: "None detected (Web Preview)",
      error: "Npcap driver required for raw packet capture",
      interfaces: ["Ethernet", "Wi-Fi", "Tailscale", "Loopback"],
    };
  },

  async startCapture(interfaceName?: string): Promise<string> {
    if (isTauriEnvironment()) {
      return await invoke("start_capture", { interfaceName });
    }
    return `Capture started on ${interfaceName || "Default"}`;
  },

  async stopCapture(): Promise<string> {
    if (isTauriEnvironment()) {
      return await invoke("stop_capture");
    }
    return "Capture stopped";
  },

  async blockRemoteIp(ip: string): Promise<string> {
    if (isTauriEnvironment()) {
      return await invoke("block_remote_ip", { ip });
    }
    return `Firewall rule for ${ip} staged (Web Preview)`;
  },

  async unblockRemoteIp(ip: string): Promise<string> {
    if (isTauriEnvironment()) {
      return await invoke("unblock_remote_ip", { ip });
    }
    return `Firewall rule for ${ip} removed (Web Preview)`;
  },
};



