// This file is generated by tauri-specta and includes browser-safe fallback handlers.
import { invoke } from "@tauri-apps/api/core";

export interface AppInfo {
  name: string;
  version: string;
  mode: string;
  isElevated: boolean;
}

export interface SystemMetrics {
  cpuUsage: number;
  ramUsedBytes: number;
  ramTotalBytes: number;
  ramUsagePercent: number;
  gpuUsage: number | null;
  gpuTemp: number | null;
  diskFreeBytes: number;
  diskTotalBytes: number;
  diskUsagePercent: number;
  dockerContainers: number;
}

const isTauriEnvironment = () => {
  return typeof window !== "undefined" && "__TAURI_INTERNALS__" in window;
};

export const commands = {
  async getAppInfo(): Promise<AppInfo> {
    if (isTauriEnvironment()) {
      return await invoke<AppInfo>("get_app_info");
    }
    return {
      name: "NetScope",
      version: "0.1.0",
      mode: "simulator",
      isElevated: false,
    };
  },

  async getSystemMetrics(): Promise<SystemMetrics> {
    if (isTauriEnvironment()) {
      return await invoke<SystemMetrics>("get_system_metrics");
    }
    // High-fidelity fallback for web previews matching target visual
    return {
      cpuUsage: 6.4,
      ramUsedBytes: 78_600_000_000,
      ramTotalBytes: 121_700_000_000,
      ramUsagePercent: 66.6,
      gpuUsage: 2.0,
      gpuTemp: 49.0,
      diskFreeBytes: 1_571_100_000_000,
      diskTotalBytes: 3_560_000_000_000,
      diskUsagePercent: 55.9,
      dockerContainers: 17,
    };
  },

  async triggerSimulation(scenario: string): Promise<string> {
    if (isTauriEnvironment()) {
      return await invoke<string>("trigger_simulation", { scenario });
    }
    return `Simulation '${scenario}' triggered`;
  },

  async cleanSimulations(): Promise<string> {
    if (isTauriEnvironment()) {
      return await invoke<string>("clean_simulations");
    }
    return "All simulations cleaned";
  },

  async setTrafficMode(mode: string): Promise<string> {
    if (isTauriEnvironment()) {
      return await invoke<string>("set_traffic_mode", { mode });
    }
    return `Mode switched to ${mode}`;
  },

  async getSocketDelta(): Promise<any> {
    if (isTauriEnvironment()) {
      return await invoke("get_socket_delta");
    }
    return {
      t: Date.now(),
      addNodes: [],
      updateNodes: [],
      removeNodeIds: [],
      addLinks: [],
      updateLinks: [],
      removeLinkIds: [],
    };
  },

  async getSocketSnapshot(): Promise<{ nodes: any[]; links: any[] }> {
    if (isTauriEnvironment()) {
      return await invoke("get_socket_snapshot");
    }
    const now = Date.now();
    const host = {
      id: "host:dark-spark",
      kind: "host",
      label: "Dark Spark (Host)",
      ip: "127.0.0.1",
      hostname: "dark-spark.local",
      firstSeen: now - 3600000,
      lastSeen: now,
      bytesIn: 45_200_000,
      bytesOut: 98_400_000,
      rateIn: 120_000,
      rateOut: 340_000,
    };
    const proc1 = {
      id: "proc:chrome",
      kind: "process",
      label: "chrome.exe",
      pid: 4892,
      exePath: "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe",
      bytesIn: 12_400_000,
      bytesOut: 2_100_000,
      rateIn: 45_000,
      rateOut: 12_000,
      firstSeen: now - 1800000,
      lastSeen: now,
    };
    const proc2 = {
      id: "proc:discord",
      kind: "process",
      label: "discord.exe",
      pid: 8120,
      bytesIn: 8_200_000,
      bytesOut: 1_800_000,
      rateIn: 18_000,
      rateOut: 5_000,
      firstSeen: now - 1800000,
      lastSeen: now,
    };
    const internet1 = {
      id: "ip:cloudflare",
      kind: "internet",
      label: "1.1.1.1 (Cloudflare)",
      ip: "1.1.1.1",
      hostname: "one.one.one.one",
      country: "US",
      bytesIn: 5_000_000,
      bytesOut: 1_000_000,
      rateIn: 15_000,
      rateOut: 4_000,
      firstSeen: now - 1800000,
      lastSeen: now,
    };
    const internet2 = {
      id: "ip:discord-cdn",
      kind: "internet",
      label: "162.159.130.233 (Discord Gateway)",
      ip: "162.159.130.233",
      country: "US",
      bytesIn: 8_000_000,
      bytesOut: 1_500_000,
      rateIn: 18_000,
      rateOut: 5_000,
      firstSeen: now - 1800000,
      lastSeen: now,
    };
    return {
      nodes: [host, proc1, proc2, internet1, internet2],
      links: [
        {
          id: "link:host->chrome",
          source: host.id,
          target: proc1.id,
          proto: "tcp",
          port: 443,
          bytesIn: proc1.bytesIn,
          bytesOut: proc1.bytesOut,
          rate: proc1.rateIn + proc1.rateOut,
          packets: 840,
          firstSeen: now - 1800000,
          lastSeen: now,
        },
        {
          id: "link:chrome->cloudflare",
          source: proc1.id,
          target: internet1.id,
          proto: "tcp",
          port: 443,
          bytesIn: internet1.bytesIn,
          bytesOut: internet1.bytesOut,
          rate: internet1.rateIn + internet1.rateOut,
          packets: 420,
          firstSeen: now - 1800000,
          lastSeen: now,
        },
        {
          id: "link:host->discord",
          source: host.id,
          target: proc2.id,
          proto: "tcp",
          port: 443,
          bytesIn: proc2.bytesIn,
          bytesOut: proc2.bytesOut,
          rate: proc2.rateIn + proc2.rateOut,
          packets: 512,
          firstSeen: now - 1800000,
          lastSeen: now,
        },
        {
          id: "link:discord->gateway",
          source: proc2.id,
          target: internet2.id,
          proto: "tcp",
          port: 443,
          bytesIn: internet2.bytesIn,
          bytesOut: internet2.bytesOut,
          rate: internet2.rateIn + internet2.rateOut,
          packets: 490,
          firstSeen: now - 1800000,
          lastSeen: now,
        },
      ],
    };
  },

  async getCaptureStatus(): Promise<{
    isAvailable: boolean;
    isActive: boolean;
    driverName: string;
    error: string | null;
    interfaces: string[];
  }> {
    if (isTauriEnvironment()) {
      return await invoke("get_capture_status");
    }
    return {
      isAvailable: false,
      isActive: false,
      driverName: "None detected (Web Preview)",
      error: "Npcap driver required for raw packet capture",
      interfaces: ["Ethernet", "Wi-Fi", "Tailscale", "Loopback"],
    };
  },

  async startCapture(interfaceName?: string): Promise<string> {
    if (isTauriEnvironment()) {
      return await invoke("start_capture", { interfaceName });
    }
    return `Capture started on ${interfaceName || "Default"}`;
  },

  async stopCapture(): Promise<string> {
    if (isTauriEnvironment()) {
      return await invoke("stop_capture");
    }
    return "Capture stopped";
  },

  async blockRemoteIp(ip: string): Promise<string> {
    if (isTauriEnvironment()) {
      return await invoke("block_remote_ip", { ip });
    }
    return `Firewall rule for ${ip} staged (Web Preview)`;
  },

  async unblockRemoteIp(ip: string): Promise<string> {
    if (isTauriEnvironment()) {
      return await invoke("unblock_remote_ip", { ip });
    }
    return `Firewall rule for ${ip} removed (Web Preview)`;
  },
};



